//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Starter.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Standard")]
        public global::Common_Library.Calculator_Mode Calculator_Mode {
            get {
                return ((global::Common_Library.Calculator_Mode)(this["Calculator_Mode"]));
            }
            set {
                this["Calculator_Mode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Single")]
        public global::Common_Library.Calculation_Method Calculation_Method {
            get {
                return ((global::Common_Library.Calculation_Method)(this["Calculation_Method"]));
            }
            set {
                this["Calculation_Method"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("510")]
        public double initial_Height {
            get {
                return ((double)(this["initial_Height"]));
            }
            set {
                this["initial_Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("420")]
        public double initial_Width {
            get {
                return ((double)(this["initial_Width"]));
            }
            set {
                this["initial_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public sbyte numeral_System {
            get {
                return ((sbyte)(this["numeral_System"]));
            }
            set {
                this["numeral_System"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::Common_Library.Number_Notation Number_Notation {
            get {
                return ((global::Common_Library.Number_Notation)(this["Number_Notation"]));
            }
            set {
                this["Number_Notation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(",")]
        public string comma_Type {
            get {
                return ((string)(this["comma_Type"]));
            }
            set {
                this["comma_Type"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("English")]
        public global::Common_Library.Languages Language {
            get {
                return ((global::Common_Library.Languages)(this["Language"]));
            }
            set {
                this["Language"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::Common_Library.Font_Size_Type Font_Size_Type {
            get {
                return ((global::Common_Library.Font_Size_Type)(this["Font_Size_Type"]));
            }
            set {
                this["Font_Size_Type"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2,8,10,12,16,60")]
        public string Pined_Numeral_Systems {
            get {
                return ((string)(this["Pined_Numeral_Systems"]));
            }
            set {
                this["Pined_Numeral_Systems"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Load_Hello_Window_Pernamently {
            get {
                return ((bool)(this["Load_Hello_Window_Pernamently"]));
            }
            set {
                this["Load_Hello_Window_Pernamently"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Load_Hello_Window_Next_Run {
            get {
                return ((bool)(this["Load_Hello_Window_Next_Run"]));
            }
            set {
                this["Load_Hello_Window_Next_Run"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Defalut")]
        public global::Common_Library.Colour_Palette_Type Colour_Palette_Type {
            get {
                return ((global::Common_Library.Colour_Palette_Type)(this["Colour_Palette_Type"]));
            }
        }
    }
}
